[package]
name = "Gemini_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.12.20" , features = ["json"]}
serde = {version = "1.0.219" , features = ["derive"]}
serde_json = "1.0.140"
